//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoEquipamentos26.administrador
{
    public partial class computadoresPortatil
    {
        /// <summary>
        /// listMarca control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList listMarca;

        /// <summary>
        /// gridComputadores control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gridComputadores;

        /// <summary>
        /// buttonVer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonVer;

        /// <summary>
        /// buttonCriar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonCriar;

        /// <summary>
        /// buttonEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonEditar;

        /// <summary>
        /// buttonEliminar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonEliminar;

        /// <summary>
        /// formularioDados control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl formularioDados;

        /// <summary>
        /// txtNome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNome;

        /// <summary>
        /// ddlMarca control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMarca;

        /// <summary>
        /// txtDescricao control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescricao;

        /// <summary>
        /// txtURL control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtURL;

        /// <summary>
        /// txtURLDrivers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtURLDrivers;

        /// <summary>
        /// uploadFoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload uploadFoto;

        /// <summary>
        /// fotoModelo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image fotoModelo;

        /// <summary>
        /// txtProcessador control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtProcessador;

        /// <summary>
        /// txtMotherboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotherboard;

        /// <summary>
        /// txtRAM control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRAM;

        /// <summary>
        /// txtArmazenamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtArmazenamento;

        /// <summary>
        /// txtPlacaGrafica control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPlacaGrafica;

        /// <summary>
        /// txtTamanhoEcra control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTamanhoEcra;

        /// <summary>
        /// txtResolucao control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtResolucao;

        /// <summary>
        /// chkEcraTatil control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkEcraTatil;

        /// <summary>
        /// chkColunasIncorporadas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkColunasIncorporadas;

        /// <summary>
        /// txtColunasNumero control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtColunasNumero;

        /// <summary>
        /// chkAuscultador control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkAuscultador;

        /// <summary>
        /// chkCamaraIncorporada control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkCamaraIncorporada;

        /// <summary>
        /// txtPortasUSB control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPortasUSB;

        /// <summary>
        /// txtPortasHDMI control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPortasHDMI;

        /// <summary>
        /// txtPortasVGA control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPortasVGA;

        /// <summary>
        /// buttonGuardar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonGuardar;

        /// <summary>
        /// buttonCancelar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonCancelar;

        /// <summary>
        /// buttonFechar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonFechar;
    }
}
