//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoEquipamentos26.administrador
{
    public partial class impressoras
    {
        protected global::System.Web.UI.WebControls.DropDownList listMarca;
        protected global::System.Web.UI.WebControls.GridView gvImpressoras;
        protected global::System.Web.UI.WebControls.Button buttonVer;
        protected global::System.Web.UI.WebControls.Button buttonCriar;
        protected global::System.Web.UI.WebControls.Button buttonEditar;
        protected global::System.Web.UI.WebControls.Button buttonEliminar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl formularioDados;
        protected global::System.Web.UI.WebControls.TextBox txtNome;
        protected global::System.Web.UI.WebControls.DropDownList ddlMarca;
        protected global::System.Web.UI.WebControls.TextBox txtDescricao;
        protected global::System.Web.UI.WebControls.TextBox txtURL;
        protected global::System.Web.UI.WebControls.TextBox txtURLDrivers;
        protected global::System.Web.UI.WebControls.FileUpload uploadFoto;
        protected global::System.Web.UI.WebControls.Image fotoModelo;
        protected global::System.Web.UI.WebControls.TextBox txtTipo;
        protected global::System.Web.UI.WebControls.TextBox txtResolucaoMaxima;
        protected global::System.Web.UI.WebControls.TextBox txtCodigoTinteiros;
        protected global::System.Web.UI.WebControls.CheckBox chkImpressaoDuplex;
        protected global::System.Web.UI.WebControls.CheckBox chkImpressaoCor;
        protected global::System.Web.UI.WebControls.CheckBox chkScanner;
        protected global::System.Web.UI.WebControls.CheckBox chkVisor;
        protected global::System.Web.UI.WebControls.CheckBox chkWifi;
        protected global::System.Web.UI.WebControls.CheckBox chkBluetooth;
        protected global::System.Web.UI.WebControls.Button buttonGuardar;
        protected global::System.Web.UI.WebControls.Button buttonCancelar;
        protected global::System.Web.UI.WebControls.Button buttonFechar;
    }
}
