//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoEquipamentos26.administrador
{
    public partial class modelos
    {
        /// <summary>
        /// listMarca control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList listMarca;

        /// <summary>
        /// listTipoEquipamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList listTipoEquipamento;

        /// <summary>
        /// gridModelos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gridModelos;

        /// <summary>
        /// buttonVer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonVer;

        /// <summary>
        /// buttonCriar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonCriar;

        /// <summary>
        /// buttonEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonEditar;

        /// <summary>
        /// formularioDados control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl formularioDados;

        /// <summary>
        /// txtNome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNome;

        /// <summary>
        /// ddlMarca control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMarca;

        /// <summary>
        /// ddlTipoEquipamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoEquipamento;

        /// <summary>
        /// txtDescricao control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescricao;

        /// <summary>
        /// txtURL control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtURL;

        /// <summary>
        /// txtURLDrivers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtURLDrivers;

        /// <summary>
        /// uploadFoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload uploadFoto;

        /// <summary>
        /// fotoModelo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image fotoModelo;

        /// <summary>
        /// buttonGuardar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonGuardar;

        /// <summary>
        /// buttonCancelar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonCancelar;

        /// <summary>
        /// buttonFechar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button buttonFechar;
    }
}
