//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoEquipamentos26.administrador
{


    public partial class monitores
    {

        /// <summary>
        /// listMarca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList listMarca;

        /// <summary>
        /// gridMonitores control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gridMonitores;

        /// <summary>
        /// buttonVer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonVer;

        /// <summary>
        /// buttonCriar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonCriar;

        /// <summary>
        /// buttonEditar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonEditar;

        /// <summary>
        /// buttonEliminar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonEliminar;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl formularioDados;
        protected global::System.Web.UI.WebControls.DropDownList ddlMarca;
        protected global::System.Web.UI.WebControls.TextBox txtNome;
        protected global::System.Web.UI.WebControls.TextBox txtDescricao;
        protected global::System.Web.UI.WebControls.TextBox txtURL;
        protected global::System.Web.UI.WebControls.TextBox txtURLDrivers;
        protected global::System.Web.UI.WebControls.FileUpload uploadFoto;
        protected global::System.Web.UI.WebControls.Image fotoModelo;
        protected global::System.Web.UI.WebControls.TextBox txtTamanho;
        protected global::System.Web.UI.WebControls.TextBox txtResolucao;
        protected global::System.Web.UI.WebControls.TextBox txtTipoHD;
        protected global::System.Web.UI.WebControls.TextBox txtTecnologiaApresentacao;
        protected global::System.Web.UI.WebControls.TextBox txtTipoPainel;
        protected global::System.Web.UI.WebControls.TextBox txtFormatoEcra;
        protected global::System.Web.UI.WebControls.TextBox txtColunasNumero;
        protected global::System.Web.UI.WebControls.CheckBox chkTactil;
        protected global::System.Web.UI.WebControls.CheckBox chkCamara;
        protected global::System.Web.UI.WebControls.TextBox txtPortasHDMI;
        protected global::System.Web.UI.WebControls.TextBox txtPortasVGA;
        protected global::System.Web.UI.WebControls.TextBox txtPortasDVI;
        protected global::System.Web.UI.WebControls.CheckBox chkSaidaAuscultador;
        protected global::System.Web.UI.WebControls.TextBox txtAltura;
        protected global::System.Web.UI.WebControls.TextBox txtComprimento;
        protected global::System.Web.UI.WebControls.TextBox txtLargura;
        protected global::System.Web.UI.WebControls.Button buttonGuardar;
        protected global::System.Web.UI.WebControls.Button buttonCancelar;
        protected global::System.Web.UI.WebControls.Button buttonFechar;
    }
}
