//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoEquipamentos26.administrador
{
    public partial class participacoes
    {
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Button btnNovaParticipacao;
        protected global::System.Web.UI.WebControls.Panel pnlNovaParticipacao;
        protected global::System.Web.UI.WebControls.DropDownList ddlLocal;
        protected global::System.Web.UI.WebControls.DropDownList ddlEquipamento;
        protected global::System.Web.UI.WebControls.TextBox txtDescricao;
        protected global::System.Web.UI.WebControls.DropDownList ddlGravidade;
        protected global::System.Web.UI.WebControls.CheckBox chkUrgente;
        protected global::System.Web.UI.WebControls.DropDownList ddlTecnico;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroLocal;
        protected global::System.Web.UI.UpdatePanel upParticipacoes;
        protected global::System.Web.UI.Timer timerRefresh;
        protected global::System.Web.UI.WebControls.Label lblPendentes;
        protected global::System.Web.UI.WebControls.Label lblResolvidas;
        protected global::System.Web.UI.WebControls.Label lblUrgentes;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.GridView gridParticipacoes;
        protected global::System.Web.UI.WebControls.Button btnAlterar;
        protected global::System.Web.UI.WebControls.Button btnEliminar;
    }
}
