//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoEquipamentos26.administrador
{
    public partial class tecnicos
    {
        protected global::System.Web.UI.WebControls.GridView gridTecnicos;
        protected global::System.Web.UI.WebControls.Button buttonVer;
        protected global::System.Web.UI.WebControls.Button buttonCriar;
        protected global::System.Web.UI.WebControls.Button buttonEditar;
        protected global::System.Web.UI.WebControls.Button buttonEliminar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl formularioDados;
        protected global::System.Web.UI.WebControls.TextBox txtNome;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtTelefone;
        protected global::System.Web.UI.WebControls.TextBox txtSenha;
        protected global::System.Web.UI.WebControls.Button buttonGuardar;
        protected global::System.Web.UI.WebControls.Button buttonCancelar;
        protected global::System.Web.UI.WebControls.Button buttonFechar;
    }
}
